apiVersion: v1
kind: Namespace
metadata:
  name: cnf-certsuite-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnf-certsuite-plugin
  namespace: cnf-certsuite-plugin
  labels:
    app: cnf-certsuite-plugin
    app.kubernetes.io/component: cnf-certsuite-plugin
    app.kubernetes.io/instance: cnf-certsuite-plugin
    app.kubernetes.io/part-of: cnf-certsuite-plugin
    app.openshift.io/runtime-namespace: cnf-certsuite-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnf-certsuite-plugin
  template:
    metadata:
      labels:
        app: cnf-certsuite-plugin
    spec:
      containers:
        - name: cnf-certsuite-plugin
          image: quay.io/rh_ee_shmoran/cnf-plugin:test2
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/cert
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
        - name: nginx-conf
          configMap:
            name: nginx-configmap
            namespace: cnf-certsuite-plugin
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: cnf-certsuite-plugin
  namespace: cnf-certsuite-plugin
  labels:
    app: cnf-certsuite-plugin
    app.kubernetes.io/component: cnf-certsuite-plugin
    app.kubernetes.io/instance: cnf-certsuite-plugin
    app.kubernetes.io/part-of: cnf-certsuite-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: cnf-certsuite-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: cnf-certsuite-plugin
  namespace: cnf-certsuite-plugin
  labels:
    app: cnf-certsuite-plugin
    app.kubernetes.io/component: cnf-certsuite-plugin
    app.kubernetes.io/instance: cnf-certsuite-plugin
    app.kubernetes.io/part-of: cnf-certsuite-plugin
spec:
  backend:
    service:
      basePath: /
      name: cnf-certsuite-plugin
      namespace: cnf-certsuite-plugin
      port: 9001
    type: Service
  displayName: OpenShift Console Demo Plugin
  i18n:
    loadType: Preload
  proxy:
    - alias: thanos-querier
      authorization: UserToken
      endpoint:
        service:
          name: thanos-querier
          namespace: openshift-monitoring
          port: 9091
        type: Service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: cnf-certsuite-plugin
  labels:
    app: cnf-certsuite-plugin
    app.kubernetes.io/component: cnf-certsuite-plugin
    app.kubernetes.io/instance: cnf-certsuite-plugin
    app.kubernetes.io/part-of: cnf-certsuite-plugin
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;
      server {
        listen              9001 ssl;
        listen              [::]:9001 ssl;
        ssl_certificate     /var/cert/tls.crt;
        ssl_certificate_key /var/cert/tls.key;
        root                /usr/share/nginx/html;
      }
    }
